version: '3'

services:

    web:
        build: ./web
        environment:
            - APACHE_RUN_USER=#1000
        volumes:
            - ${APP_PATH_HOST}:${APP_PATH_CONTAINER}
        ports:
            - 8080:80
        working_dir: ${APP_PATH_CONTAINER}

    db:
        image: mysql:5.7
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: secret
        volumes:
            - ${DB_PATH_HOST}:/var/lib/mysql

    adminer:
        image: adminer
        restart: always
        ports:
            - 8081:8080

#    composer:
#        image: composer/composer
#        volumes:
#            - ${APP_PATH_HOST}:${APP_PATH_CONTAINER}
#        working_dir: ${APP_PATH_CONTAINER}
#        command: composer install
